steps:
    build:
        image: woodpeckerci/plugin-docker-buildx
        settings:
            dockerfile: Dockerfile
            repo: your-repo-name
            tags: latest
        when:
            event: push
            branch: main
