services:
  app:
    build: .
    image: 532financeappacr.azurecr.io/532-finance-app:latest
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/532-networth-app
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_USEPOLLING=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 532-networth-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
